### ISSUE TITLE
android-23, Constant expression required

### ISSUE THREAD

**Issue by atship** [anggrayudi/android-hidden-api#10]
这个变量会报错 MeasureSpec.UNSPECIFIED
```
switch (MeasureSpec.getMode(measureSpec)) {
            case MeasureSpec.UNSPECIFIED:
                result = desired;
                break;
            case MeasureSpec.AT_MOST:
                result = Math.max(specSize, desired);
                break;
            case MeasureSpec.EXACTLY:
            default:
                result = specSize;
        }
```

**Comment by anggrayudi** [comment]
what do you mean? Can you explain well?

**Comment by atship** [comment]
Oh, sorry...
the MeasureSpec.UNSPECIFIED will cause a compile error: Constant expression required
because the switch statement require a constant expression.
My guess is that, the android.jar has a static field for MeasureSpec.UNSPECIFIED, but not static final

**Comment by anggrayudi** [comment]
Seems that this issue is not active anymore, I will close it now.

**Comment by sandiAndi** [comment]
Hi, 
I am facing this issue, when i used android-23 jar.

**Comment by DanielKaparunakis** [comment]
I also encountered this issue when using the JAR for API level 23. In case you're interested, [here](https://devmaze.wordpress.com/2011/01/18/using-com-android-internal-part-1-introduction/) is a tutorial on how to build your own custom JAR.

**Comment by gongzelong0718** [comment]
same problem
