### ISSUE TITLE
android 22, cannot resolve AbsListView.OnScrollListener

### ISSUE THREAD

**Issue by gitzxon** [anggrayudi/android-hidden-api#11]
hi,

I came across a compile error "Can not resolve AbsListView.OnScrollListener" when I try to make SomeClass implements AbsListView.OnScrollListener.

thx

**Comment by gitzxon** [comment]
I changed the android.jar to the original android.jar provided by android, and it compiled successfully.

**Comment by anggrayudi** [comment]
Have you tried with android 23?

**Comment by gitzxon** [comment]
I test it on android 23 with hidden api and it works well.
