### ISSUE TITLE
can`t find CallManager  class,why?what should i do?

### ISSUE THREAD

**Issue by ccxclin** [anggrayudi/android-hidden-api#12]

**Comment by anggrayudi** [comment]
Have you tried with the latest version (android-23) ?

**Comment by ccxclin** [comment]
yes

**Comment by anggrayudi** [comment]
Please follow the instruction as described [here](https://github.com/anggrayudi/android-hidden-api#usage). But if the error still happen, attach the detail, i.e. Android Studio version, etc.

**Comment by anggrayudi** [comment]
Have the problem resolved?

**Comment by anggrayudi** [comment]
Seems that this issue is no longer active. I will close it.
