### ISSUE TITLE
Can't find mms package under com.google.android

### ISSUE THREAD

**Issue by marcelolima** [anggrayudi/android-hidden-api#15]
First of all, thanks for sharing those jars.
My issue is that I'm trying to use the hidden API com.google.android.mms but it isn't available on the downloaded jar for API 23.

**Comment by anggrayudi** [comment]
`com.google.android.mms` is a Google's library for Android while Android hidden APIs only support non-library package. The proof is you can add this package to `build.gradle` of your app's module, e.g:

````gradle
dependencies {
    compile 'com.google.android.gms:play-services-ads:9.0.2'
}
````

If you really need to use the hidden classes from `com.google.android.mms`, we still have an alternative, i.e. using [Java reflection](http://www.programcreek.com/2013/09/java-reflection-tutorial/).

**Comment by marcelolima** [comment]
Hi Anggrayudi,

Thanks! FYI, I'm trying to compile this test from Android CTS suite outside the CTS package:

https://android.googlesource.com/platform/cts/+/5623639ce9a6b52413ae429f49599a1d937ad3c3/tests/tests/telephony/src/android/telephony/cts/MmsTest.java
