### ISSUE TITLE
when you used databinding in your project,it will cause 'xxx.xxx.xxx.databinding not exist' exception when building

### ISSUE THREAD

**Issue by aishang5wpj** [anggrayudi/android-hidden-api#16]
如果项目使用了databinding的话，把本地sdk替换成这里的android.jar将会导致编译时提示"xxx.xxx.xxx.databinding"不存在的错误提示，导致编译无法通过。
和leader一起弄了一下午，最后发现是这个问题。
醉了。

**Comment by anggrayudi** [comment]
What did you say? Please speak in English.
