### ISSUE TITLE
Can't import classes from com.android.internal

### ISSUE THREAD

**Issue by KilBirDIh** [anggrayudi/android-hidden-api#18]
Hello, I added your jar for 23 API, added dependecies and repository, tried to rebuild the project and get error:
Error:Execution failed for task ':app:mockableAndroidJar'.

> java.lang.NullPointerException (no error message)
> Also classes from com.android.internal AS can't see, can you help to fix this?

**Comment by realmgate** [comment]
I am also encountering this issue on Android Studio 2.2.2.  Whenever I try any clean or build operation this same error occurs.  I am trying to use the 19 API.

**Comment by anggrayudi** [comment]
Please use Hidden API v24 to fix this problem.
