### ISSUE TITLE
Can't work

### ISSUE THREAD

**Issue by JackLauu** [anggrayudi/android-hidden-api#2]
When I use the android.jar (API 22) in your project, I get a error:
> Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '\Android\sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1
I don't know why, what's more, the built-in type can't be recognized and need import, like String int and more. I don't know why. 

My IDE is Android Studio, update to the latest.

**Comment by anggrayudi** [comment]
Do you use Support Library revision 23.x.x in your project?

**Comment by JackLauu** [comment]
That's right, may be it's the problem. In android 6.0, there are nothing in the framework.jar, maybe it's the /system/framework/arm/boot.oat?

**Comment by anggrayudi** [comment]
`framework.jar` only available on real device, instead of emulator device.

Since Support Library 23.x.x was released, you need to have `compileSdkVersion 23` and `targetSdkVersion 23`, but hidden API is limited to API level 22. If you have a real 6.0 device, please upload it to me. I will make it available for API 23.

**Comment by wasdennnoch** [comment]
The problem with the framework.jar is that it contains no classes.dex file. Many othe people have the same "issue", and no, not in emulators, on real devices. The boot.oat seems to extract the classes.dex files to /system/framework/oat/arm/. Every odex file is there - except for the framework.(o)dex. I don't know if cm is causing this, but I don't have this file. Sorry :(
