### ISSUE TITLE
How to make sdk includes @hide annotation

### ISSUE THREAD

**Issue by LysonLuo** [anggrayudi/android-hidden-api#22]
Hi ,Can you describe how to make my own sdk with @hide annotation ?  Whick  mk file should I modify?please tell me ,Thank you !

**Comment by anggrayudi** [comment]
Although you add your own jar with _@hide_ annotation, this never make any changes. You cannot do this.

What actually you see in the Android SDK with this annotation is telling you that classes, methods and resources only exist in the `framework.jar`, and they exist in Android SDK sources jar (available in documentation only) which means you cannot use them. What I did to make us able to use this hidden API is combining the missing classes, methods and resources from `framework.jar` into `android.jar` placed in `<SDK-path>/platforms/`
