### ISSUE TITLE
24 compile error

### ISSUE THREAD

**Issue by jp1017** [anggrayudi/android-hidden-api#24]
Error:(50, 20) error: cannot access Editable
bad class file: /home/jp/Android/Sdk/platforms/android-24/android.jar(android/text/Editable.class)
default method found in version 50.0 classfile
Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by anggrayudi** [comment]
English please...

**Comment by jp1017** [comment]
@anggrayudi 

You can add this code to test:

```
mEditText.addTextChangedListener(new TextWatcher(){
.......
});
```

**Comment by Trumeet** [comment]
I have also encountered this error
```
Error: Unable to access Editable
Wrong class file: My android.jar(android/text/Editable.class)
Find the default method in the 50.0 version of the class file
Delete the file or make sure that the file is in the correct classpath subdirectory.
```

**Comment by anggrayudi** [comment]
This issue was fixed in hidden API v25.

**Comment by jp1017** [comment]
Well done. It works well, Thanks. :smile: :+1:
