### ISSUE TITLE
SDK 25 framework.jar

### ISSUE THREAD

**Issue by aviraxp** [anggrayudi/android-hidden-api#25]
Taken from CM14.1, not a very good source but useable.

https://drive.google.com/open?id=0Bxhk8H_5bn54d1dUR2xrYWZuT2s

**Comment by jakubturcovsky** [comment]
Any updates? I'd be great to have android.jar for API 25.

**Comment by minhdangoz** [comment]
Use this version of mine
https://goo.gl/08ZeXy

**Comment by jakubturcovsky** [comment]
@minhdangoz There's only one folder named android-24. I'm looking for version 25.

**Comment by anggrayudi** [comment]
@jakubturcovsky I'm facing heavy tasks from my lecturer. I hope you can be patient until this Friday for the new version of hidden API.
Thanks.

**Comment by AndroidDeveloperLB** [comment]
I can send it if you wish. Where to look for it?

**Comment by anggrayudi** [comment]
We just released hidden API v25. Check it out!
