### ISSUE TITLE
default method found in version 50.0 classfile

### ISSUE THREAD

**Issue by minhdangoz** [anggrayudi/android-hidden-api#28]
Error:(19, 20) error: cannot access Editable
bad class file: D:\ANDROID\DEVELOPMENT\ADT\sdk\platforms\android-24\android.jar(android/text/Editable.class)
default method found in version 50.0 classfile
Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by jp1017** [comment]
Similar to this: https://github.com/anggrayudi/android-hidden-api/issues/24

**Comment by minhdangoz** [comment]
Yes, it's same.

**Comment by minhdangoz** [comment]
Already fixed, using this version.
https://goo.gl/08ZeXy
please check and update if needed

**Comment by anggrayudi** [comment]
This issue was fixed in hidden API v25.
