### ISSUE TITLE
About API 25...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [anggrayudi/android-hidden-api#29]
I get this:

D:\Desktop\android-hidden-api\sample\android-hidden-api\src\main\java\com\anggrayudi\hiddenapi\InternalAccessor.java
Error:(43, 73) error: package com.android.internal.R does not exist
Error:(44, 73) error: package com.android.internal.R does not exist
Error:(45, 73) error: package com.android.internal.R does not exist
Error:(46, 73) error: package com.android.internal.R does not exist
Error:(47, 73) error: package com.android.internal.R does not exist
Error:(48, 73) error: package com.android.internal.R does not exist
Error:(49, 73) error: package com.android.internal.R does not exist
Error:(50, 73) error: package com.android.internal.R does not exist
Error:(51, 73) error: package com.android.internal.R does not exist
Error:(52, 73) error: package com.android.internal.R does not exist
Error:(53, 73) error: package com.android.internal.R does not exist
Error:(54, 73) error: package com.android.internal.R does not exist
Error:(55, 73) error: package com.android.internal.R does not exist
Error:(56, 73) error: package com.android.internal.R does not exist
Error:(57, 73) error: package com.android.internal.R does not exist
Error:(58, 73) error: package com.android.internal.R does not exist
Error:Execution failed for task ':android-hidden-api:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by anggrayudi** [comment]
You created issue before I release hidden API v25. I will close it now.

**Comment by AndroidDeveloperLB** [comment]
I don't understand.

**Comment by AndroidDeveloperLB** [comment]
I still see this issue. Why close it?

**Comment by jakubturcovsky** [comment]
@AndroidDeveloperLB Because you couldn't see issue on API 25 before it was even released. Duh.

**Comment by AndroidDeveloperLB** [comment]
@jakubturcovsky So why close before instead of after? And why be rude?
Anyway, thanks to dev.

**Comment by AndroidDeveloperLB** [comment]
Now I've checked recent version. I still get this error.
Why close the issue?
