### ISSUE TITLE
Having build error

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [anggrayudi/android-hidden-api#30]
When importing and trying to build the sample project, I get this error:

Information:Gradle tasks [:app:assembleDebug]
C:\Users\User\Desktop\android-hidden-api\sample\android-hidden-api\src\main\java\com\anggrayudi\hiddenapi\InternalAccessor.java
Error:(43, 73) error: package com.android.internal.R does not exist
Error:(44, 73) error: package com.android.internal.R does not exist
Error:(45, 73) error: package com.android.internal.R does not exist
Error:(46, 73) error: package com.android.internal.R does not exist
Error:(47, 73) error: package com.android.internal.R does not exist
Error:(48, 73) error: package com.android.internal.R does not exist
Error:(49, 73) error: package com.android.internal.R does not exist
Error:(50, 73) error: package com.android.internal.R does not exist
Error:(51, 73) error: package com.android.internal.R does not exist
Error:(52, 73) error: package com.android.internal.R does not exist
Error:(53, 73) error: package com.android.internal.R does not exist
Error:(54, 73) error: package com.android.internal.R does not exist
Error:(55, 73) error: package com.android.internal.R does not exist
Error:(56, 73) error: package com.android.internal.R does not exist
Error:(57, 73) error: package com.android.internal.R does not exist
Error:(58, 73) error: package com.android.internal.R does not exist
Error:org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.

**Comment by anggrayudi** [comment]
Already fixed in v0.0.7

**Comment by AndroidDeveloperLB** [comment]
@anggrayudi Now I get this error:

D:\Desktop\android-hidden-api\sample\app\src\main\java\com\anggrayudi\hiddenapi\sample\MainActivity.java
Error:(4, 19) error: cannot find symbol class EthernetManager
Error:(51, 28) error: cannot find symbol method formatShortElapsedTime(MainActivity,int)
Error:(91, 13) error: cannot find symbol class EthernetManager
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by anggrayudi** [comment]
@AndroidDeveloperLB Please use custom `android.jar` as described in [Usage](https://github.com/anggrayudi/android-hidden-api#usage) with 4 steps.

**Comment by AndroidDeveloperLB** [comment]
oh ok. Isn't there a better solution for this though?

**Comment by anggrayudi** [comment]
@AndroidDeveloperLB I don't know exactly when. But when it comes and you have Android O physical device, you can send `framework.jar` file to me, and I will make it available for Android O.

**Comment by AndroidDeveloperLB** [comment]
@anggrayudi It's already available on the SDK. Here:
https://expirebox.com/download/e46e2bc6f6dc48fe1e53d5655da1aba3.html
What exactly do you do with them? Remove the "hide" annotation?
You have to have it on a real device? If so, from which path?

**Comment by anggrayudi** [comment]
@AndroidDeveloperLB You don't understand on how to create `android.jar`. I have no time to explain it.

**Comment by AndroidDeveloperLB** [comment]
ok, but was the file I've shared of any help?
