### ISSUE TITLE
Cannot build with android-22 due to aapt error

### ISSUE THREAD

**Issue by burningthumb** [anggrayudi/android-hidden-api#4]
The attached simple project builds just fine against the standard android-22 but when I replace the android.jar it fails to build with an aapt error stating android.jar not found.

Any ideas?

[SimpleTest.zip](https://github.com/anggrayudi/android-hidden-api/files/166583/SimpleTest.zip)

**Comment by JackLauu** [comment]
It's the problem we use support library with 23.x.x. I have nexus 5 and update to android 6.0, but the framework.jar it's only 1KB.

**Comment by anggrayudi** [comment]
@burningthumb this error was discussed in issue #2.

@JackLauu only some real devices having `framework.jar` with full size. This is why making Android Hidden API project little difficult. Finding someone who have pure `framework.jar` 6.0 almost impossible.

**Comment by anggrayudi** [comment]
> Does this mean if I use build tools
23.x.x and support libraries 23.x.x it will work?

@burningthumb Any versions of build tools will work, but as this hidden API level only available up to 22, you cannot use Support Library 23.x.x.
