### ISSUE TITLE
Cannot access some resources

### ISSUE THREAD

**Issue by ben221199** [anggrayudi/android-hidden-api#40]
I cannot access some resources. For example: `@android:attr/theme` is accessable, but `@android:attr/pointerStyle` isn't. However, when you look with APK Tool, the identifier exists in resources.arsc. I would like to see this resources unhidden.

**Comment by anggrayudi** [comment]
You are only able to access resources from class `com.android.internal.R`. I have no idea to access resources from another `R` file.

**Comment by ben221199** [comment]
Ok, I think some entries should be added to the ``android.R`` class to make some resources public.
