### ISSUE TITLE
android-23 will cause build error Constant expression required

### ISSUE THREAD

**Issue by gongzelong0718** [anggrayudi/android-hidden-api#41]
I am using android-23 jar.

```
switch (MeasureSpec.getMode(measureSpec)) {
            case MeasureSpec.UNSPECIFIED:
                result = desired;
                break;
            case MeasureSpec.AT_MOST:
                result = Math.max(specSize, desired);
                break;
            case MeasureSpec.EXACTLY:
            default:
                result = specSize;
        }

```
MeasureSpec.UNSPECIFIED will cause a compile error: Constant expression required
because the switch statement require a constant expression.

This bug is not fixed. There is a same issue closed but not fixed.

https://github.com/anggrayudi/android-hidden-api/issues/10

**Comment by anggrayudi** [comment]
Tested on Android Studio 3.2.1 and android-28.jar. No compile error.
