### ISSUE TITLE
please add android-28

### ISSUE THREAD

**Issue by andylqzhang** [anggrayudi/android-hidden-api#43]
Thanks!

**Comment by anggrayudi** [comment]
Sorry, I have no device with Android Pie. Everyone can send `framework.jar` here and I will make it for you.

**Comment by MrWhite214** [comment]
> Sorry, I have no physical device with Android Pie. Everyone can send `framework.jar` here and I will make it for you.


 
[framework.zip](https://github.com/anggrayudi/android-hidden-api/files/2484249/framework.zip)

Device: Oneplus 3T
ROM: LineageOS 16
Date of ROM: Mon Sep 10 2018

**Comment by StormGens** [comment]
Please ~~~~

**Comment by let-aurn** [comment]
@anggrayudi Can you share how to? Is this just about removing the `@hide` annotations and rebuild the jar?

**Comment by anggrayudi** [comment]
Did it!

**Comment by anggrayudi** [comment]
Sorry to make you wait. I was really busy. Now, you can use Hidden APIs v28.0

**Comment by anggrayudi** [comment]
@let-aurn No, it is not that easy Ferguso. You need to replace all hidden classes from original `android.jar` with classes from `framework.jar`.
