### ISSUE TITLE
How to merge android.jar and framework.jar?

### ISSUE THREAD

**Issue by ksmith3036** [anggrayudi/android-hidden-api#47]
This work looks really impressive! 
I am using an Android phone with some extended API's, so the android.jar file exposes a few more classes and methods than normal. 
The effect is that I cannot use the android.jar files published here, but will have to merge android.jar and framework.jar myself. 
Could you please share information about how to do this?

**Comment by anggrayudi** [comment]
Hello @ksmith3036, I have wrote it here:
https://medium.com/@hardiannicko/create-your-own-android-hidden-apis-fa3cca02d345
Check it out!
