### ISSUE TITLE
Building v22

### ISSUE THREAD

**Issue by botondbutuza** [anggrayudi/android-hidden-api#5]
Hey there!

First of all, many thanks for getting v22 up, it going to save me so much time once it compiles!

I've managed to get v21 running, but I need v22, so I grabbed it, and whacked it in /sdk/platform/android-22, but I cannot get it to compile. I looked at the previous issues raised here, and my problem is not that I'm using v23 build tools. This is my gradle file:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.0"

    defaultConfig {
        applicationId "REDACTED"
        minSdkVersion 22
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:22.0.+'
}
```

As you can see, AppCompat is 22, compileVersion is 22, buildTools is 22, everything is 22. The issue gradle is reporting:

```
Execution failed for task ':app:processDebugResources'.
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/botondbutuza/Library/Android/sdk/build-tools/22.0.0/aapt'' finished with non-zero exit value 1
```

The first line of the exception thrown with --debug and --stacktrace is

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugResources'.
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
```

Not sure if that helps, but there it is.

Any help would be greatly appreciated. Have you managed to build a project with v22?

**Comment by anggrayudi** [comment]
May be there is something wrong with `framework.jar` in previous device. I will try to get `framework.jar` from different device and rebuild it later.

Just watch this repository to know any changes.

**Comment by botondbutuza** [comment]
Did you manage to build a project with v22? I tried creating my own android.jar from 22 a month or so ago, and I ran into the same problem as the one reported above, so it's very interesting.

**Comment by burningthumb** [comment]
I think its very strange.  Just for fun, on v22 I unzipped the Android.jar and then re-zipped it.  Then I get the error.  I did not even change it. I literally just renamed it to a zip, unzipped it, zipped the folder, and renamed it back to a jar.  Maybe that provides a clue ?

**Comment by botondbutuza** [comment]
I haven't done anything like that, just downloaded it, and popped it in.

**Comment by burningthumb** [comment]
It seems this problem is known at least one month ago (maybe this is yours botondbutuza):
http://stackoverflow.com/questions/34811406/accessing-android-5-1-internal-apis

**Comment by botondbutuza** [comment]
Yupp that was my attempt at building my own jar file. Ran into the same issue.

**Comment by burningthumb** [comment]
Did you see/try the method in the post by corochann?  In his screen shots it looks like he is using sdk-22:
http://corochann.com/importing-android-sdk-with-hidden-apis-493.html

**Comment by JackLauu** [comment]
@anggrayudi Would you please commit a complete sample project？Your sample only have gradle files. When I create my project, I found that I can only use the android support 23 library. I tried many ways but couldn't solve it, please try and get it, thank you very much.

**Comment by anggrayudi** [comment]
Dear all, I already fixed android-22 jar. You can use it now.

@JackLauu I'm developing the sample project now. Just wait until I upload it.

**Comment by burningthumb** [comment]
Please see my issue #6 on the correct build.gradle file to use with 
appcompat libraries and the hidden api 22.
