### ISSUE TITLE
android hidden api for android 28

### ISSUE THREAD

**Issue by yoshida-be** [anggrayudi/android-hidden-api#50]
I using your android hidden api for android 28 and found some bug.
it does not contain IPackageInstallObserver interface and PackageManager class doesnot contain installPackage method.
My application work well with android hidden api version 27
could you please check and fix it
Thanks

**Comment by yoshida-be** [comment]
@anggrayudi could you please check and help me.

**Comment by yoshida-be** [comment]
@anggrayudi @johnjohndoe @Trumeet could you please check this issue?

**Comment by anggrayudi** [comment]
It is not a bug. It is a drawback of Hidden API and we cannot fix it. Some classes, methods, or resources may be available on certain API level, and there is no guarantee that they'll still exist in the current level. You must be aware of using Hidden API. If needed, you can copy the code of Hidden API into your project. Hidden API is only a bridge for you to see and copy the complete code.

**Comment by yoshida-be** [comment]
> If needed, you can copy the code of Hidden API into your project. Hidden API is only a bridge for you to see and copy the complete code.

@anggrayudi could you please share me code of Hidden API, i want to intergrate into my project
