### ISSUE TITLE
android26.jar compile err

### ISSUE THREAD

**Issue by DarkSherlock** [anggrayudi/android-hidden-api#52]
Could not resolve all files for configuration ':app:androidApis'.
Failed to transform file 'android.jar' to match attributes {artifactType=android-mockable-jar, returnDefaultValues=false} using transform MockableJarTransform

studio show this error message when i replace the android.jar of android-26

**Comment by anggrayudi** [comment]
This issue comes since Android Studio v3.2. I have no idea for the solution.

**Comment by anggrayudi** [comment]
Closed as duplicate of #46
