### ISSUE TITLE
Sample project with appcompat for android-22

### ISSUE THREAD

**Issue by burningthumb** [anggrayudi/android-hidden-api#6]
So I think the issue with android-22 comes down to the fact that, if you have an sdk beyond 22 installed, the Android Studio project wizard is a bit dense when in creates the build.gradle file for the module.   Specifically it uses the later api  com.android.support libraries.  

If you uninstall later sdk's then the wizard generates the correct build.gradle file for the module that works with the hidden-api.  I would like to suggest that you document the build.gradle requirements for the module for each API.  But maybe it should be obvious.  In any case for android-22 I have attached a sample project that builds with the main issue being the build.gradle for the module that will work is this:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.burningthumb.simpletest"
        minSdkVersion 22
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.android.support:design:22.2.1'
}
```

[SimpleTest.zip](https://github.com/anggrayudi/android-hidden-api/files/170047/SimpleTest.zip)

**Comment by anggrayudi** [comment]
I have updated the sample project. Also, I have added _Internal Accessor_ to make us able to retrieve internal Android resources.
