### ISSUE TITLE
Will this project be updated to Android 10？

### ISSUE THREAD

**Issue by ghost** [anggrayudi/android-hidden-api#63]

**Comment by anggrayudi** [comment]
I am not sure. But if you have `android.jar` from Android 10, then I will make it available for you.

**Comment by Richyeohx** [comment]
Can I send it to you by email?

**Comment by Richyeohx** [comment]
Files on Github are slowly downloaded in China.

**Comment by tateisu** [comment]
this is PH-1's /system/framework folder.
http://nextcloud.cross.lol/s/ZmWQFCHxNSWjH4J

**Comment by ikalkov** [comment]
Can you create a readme how to generate such jars? Maybe others will create pull requests for newer versions.

**Comment by tateisu** [comment]
see unresolved issue #46 
Maybe we were stranded

**Comment by Reginer** [comment]
[android29.jar](https://github.com/Reginer/File/raw/master/android29.rar)  which I use.
unzip it, try 1 try

**Comment by anggrayudi** [comment]
@ikalkov I will provide the tutorial later. Maybe on this Saturday or Sunday.

**Comment by anggrayudi** [comment]
`android-29` has been uploaded here https://github.com/anggrayudi/android-hidden-api/commit/b4b57a46783393dd5978f660d365cca456d3eafd
Thanks to @Reginer

**Comment by DonMorr** [comment]
@anggrayudi Did you get a chance to provide the tutorial? Thank you
