### ISSUE TITLE
API 26 crashes

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [anggrayudi/android-hidden-api#66]
Hello, I tried your jars because I need the createL2capSocket() function from android.bluetooth.BluetoothDevice. But the application crashed giving me this output : 
(I'm using QtCreator, outputs are different from Android Studio) 

`
I         : power log dlsym ok
I zygote  : Late-enabling -Xcheck:jni
D ActivityThread: ActivityThread,attachApplication
D HwFLClassLoader: get used feature list :/feature/used-list failed!
D HwFLClassLoader: USE_FEATURE_LIST had not init!
I HwApiCacheMangerEx: apicache mCurPackageName=org.scotthamilton.wiimote uptimes=22450261
I HwApiCacheMangerEx: apicache oUid null
I HwApiCacheMangerEx: apicache volumes null
I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=org.scotthamilton.wiimote#10172#256
I HwApiCacheMangerEx: apicache path=/storage/F25E-151D state=mounted key=org.scotthamilton.wiimote#10172#256
I HwApiCacheMangerEx: apicache oUid 10172
I HwApiCacheMangerEx: apicache volumes null
I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=org.scotthamilton.wiimote#10172#0
I HwApiCacheMangerEx: apicache path=/storage/F25E-151D state=mounted key=org.scotthamilton.wiimote#10172#0
I HwApiCacheMangerEx: apicache async read begin packageName=org.scotthamilton.wiimote userid=0
I HwApiCacheMangerEx: apicache pi null
I chatty  : uid=10172(u0_a172) queued-work-loo identical 1 line
I HwApiCacheMangerEx: apicache pi null
I HwApiCacheMangerEx: apicache oUid null
I HwApiCacheMangerEx: apicache async read finished packageName=org.scotthamilton.wiimote userid=0 totalus=18216
I HwApiCacheMangerEx: apicache pi null
E Minikin : Could not get cmap table size!
E MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
W amilton.wiimote: type=1400 audit(0.0:35298): avc: denied { write } for name="hwlog_exception" dev="tmpfs" ino=16569 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:hw_exception_dev:s0 tclass=chr_file permissive=0
I HwCust  : Constructor found for class android.app.HwCustActivityImpl
D HwCust  : Create obj success use class android.app.HwCustActivityImpl
V HwPolicyFactory: : success to get AllImpl object and return....
V ActivityThread: ActivityThread,callActivityOnCreate
V HwWidgetFactory: : successes to get AllImpl object and return....
I HwApiCacheMangerEx: apicache pi PackageInfo{3ff9882 org.scotthamilton.wiimote}
W System  : ClassLoader referenced unknown path:
D HwGalleryCacheManagerImpl: mIsEffect:false
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
W WindowDecorActionBar: should not do the transition or the transition anim is null or it is running or the mContainer view is null or mContainer view hasn't been drawn to screen
I QtCore  : Start
W linker  : "/data/app/org.scotthamilton.wiimote-WkmwTQRHj4_zmpnl4OR_8A==/lib/arm/libQt5AndroidExtras.so" has unsupported flags DT_FLAGS_1=0x80
W linker  : "/data/app/org.scotthamilton.wiimote-WkmwTQRHj4_zmpnl4OR_8A==/lib/arm/libQt5Gui.so" has unsupported flags DT_FLAGS_1=0x80
W linker  : "/data/app/org.scotthamilton.wiimote-WkmwTQRHj4_zmpnl4OR_8A==/lib/arm/libQt5Widgets.so" has unsupported flags DT_FLAGS_1=0x80
W linker  : "/data/data/org.scotthamilton.wiimote/qt-reserved-files/plugins/platforms/android/libqtforandroid.so" has unsupported flags DT_FLAGS_1=0x80
I Qt      : qt started
I zygote  : Do partial code cache collection, code=31KB, data=27KB
I zygote  : After code cache collection, code=30KB, data=26KB
I zygote  : Increasing code cache capacity to 128KB
I zygote  : Do partial code cache collection, code=57KB, data=56KB
I zygote  : After code cache collection, code=57KB, data=56KB
I zygote  : Increasing code cache capacity to 256KB
I zygote  : Do full code cache collection, code=125KB, data=99KB
I zygote  : After code cache collection, code=117KB, data=84KB
W System.err: java.lang.Exception:
W System.err: 	at org.qtproject.qt5.android.bindings.QtLoader.loadApplication(QtLoader.java:243)
W System.err: 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:697)
W System.err: 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:183)
W System.err: 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:266)
W System.err: 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:273)
W System.err: 	at android.app.Activity.performCreate(Activity.java:7383)
W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
W System.err: 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:108)
W System.err: 	at android.os.Looper.loop(Looper.java:166)
W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
W System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
D HwRTBlurUtils: check blur style for HwPhoneWindow, themeResId : 0x010303d9, context : android.view.ContextThemeWrapper@1014629, Nhwext : 0, get Blur : disable with , null
I HwSecImmHelper: mSecurityInputMethodService is null
D OpenGLRenderer:   HWUI Binary is  disabled
D OpenGLRenderer: HWUI GL Pipeline
D ActivityThread: add activity client record, r= ActivityRecord{170496b token=android.os.BinderProxy@fa42f6 {org.scotthamilton.wiimote/org.scotthamilton.wiimote.MyActivity}} token= android.os.BinderProxy@fa42f6
I zygote  : Do partial code cache collection, code=119KB, data=105KB
I zygote  : After code cache collection, code=119KB, data=105KB
I zygote  : Increasing code cache capacity to 512KB
I PressGestureDetector: onAttached begin
I PressGestureDetector: onAttached end
I PressGestureDetector: HiTouch restricted: AboardArea.
I Adreno  : QUALCOMM build                   : 00d0768, Ie4790512f3
I Adreno  : Build Date                       : 06/25/18
I Adreno  : OpenGL ES Shader Compiler Version: EV031.20.00.04
I Adreno  : Local Branch                     :
I Adreno  : Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.5.R1.08.00.00.312.030
I Adreno  : Remote Branch                    : NONE
I Adreno  : Reconstruct Branch               : NOTHING
I PressGestureDetector: onAttached begin
I PressGestureDetector: onAttached end
I PressGestureDetector: HiTouch restricted: AboardArea.
I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
I iGraphics: [0020080c] pn: org.scotthamilton.wiimote, p: 23966
E iGraphics: failed to load file: /product/etc/xml/igraphics_config_cust.xml
I iGraphics: [0030080c] opt app: 0
I OpenGLRenderer: Initialized EGL, version 1.4
D OpenGLRenderer: Swap behavior 2
E vndksupport: Could not load vendor/lib/egl/libGLES_mali.so from sphal namespace: dlopen failed: library "vendor/lib/egl/libGLES_mali.so" not found.
I zygote  : Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
D OpenGLRenderer:   HWUI Binary is  disabled
D OpenGLRenderer:   HWUI Binary is  disabled

"org.scotthamilton.wiimote" died.`

**Comment by liangxiwei** [comment]
it seem not the jar problem. you can try to  use reflect api to do what you want and see it work or not.

**Comment by SCOTT-HAMILTON** [comment]
Not sure to understand what the reflect API has to do with this issue. Thanks anyway, I gave up on this, closing the issue.
