### ISSUE TITLE
Framework.jar for Android 6

### ISSUE THREAD

**Issue by amalChandran** [anggrayudi/android-hidden-api#7]
I extracted the framework.jar file from nexus 6p. Hope it helps. https://drive.google.com/file/d/0B4Sf9EwVaZ6jY1RlbmNhaHZROFU/view?usp=sharing

**Comment by anggrayudi** [comment]
@amalChandran Did you pick the jar from emulator? I wonder why the jar less than 5MB.

**Comment by amalChandran** [comment]
Does it vary if its emulator. I did take it from android n preview from nexus 6p emulator.

**Comment by anggrayudi** [comment]
Yes, it's vary. Try to open the jar with WinRar and you'll see that this jar doesn't contain `classes.dex` file.
