### ISSUE TITLE
Android 10(API29) needed

### ISSUE THREAD

**Issue by excitedhaha** [anggrayudi/android-hidden-api#70]

**Comment by Reginer** [comment]
[android29.jar](https://github.com/Reginer/File/raw/master/android29.rar)  which I use.
unzip it, try 1 try

**Comment by anggrayudi** [comment]
Did the file you @Reginer share is a customized JAR that has been combined with `framework.jar`?

**Comment by Reginer** [comment]
I think it's been combined .  

`android.media.AudioAttributes`   is  different

**Comment by anvyal** [comment]
@anggrayudi, can you please update API29 in the repo?

**Comment by anggrayudi** [comment]
Uploaded here @anvyal, https://github.com/anggrayudi/android-hidden-api/commit/b4b57a46783393dd5978f660d365cca456d3eafd

Thanks @Reginer

**Comment by anvyal** [comment]
Thanks a lot @anggrayudi.. This project of yours is very useful.. !!
