### ISSUE TITLE
Instructions for creating the Android.jar files with hidden API

### ISSUE THREAD

**Issue by DonMorr** [anggrayudi/android-hidden-api#72]
Hi @anggrayudi ,
Could you please provide some basic instructions on how to generate the Android.jar file with hidden APIs? I'm working on a custom Android platform and would like to know how to do this.
Thank you for your help,
Donal

**Comment by anggrayudi** [comment]
Hello @DonMorr, I have wrote it here:
https://medium.com/@hardiannicko/create-your-own-android-hidden-apis-fa3cca02d345
Check it out!

**Comment by DonMorr** [comment]
Hi @anggrayudi, Excellent, thank you for sharing this!
Best regards,
Donal
