### ISSUE TITLE
Android30.jar download

### ISSUE THREAD

**Issue by Reginer** [anggrayudi/android-hidden-api#78]
[android30.7z](https://github.com/Reginer/File/raw/master/android30.7z)

unzip it

**Comment by anggrayudi** [comment]
Is this JAR ready to be used as hidden API, or should we combine it with `framework.jar` first?

**Comment by Reginer** [comment]
Has merged  out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar  and android.jar .

**Comment by anggrayudi** [comment]
From which device you obtained the `framework.jar`?

**Comment by Reginer** [comment]
classes-header.jar is framework.jar。
aosp android-11.0.0_r3

**Comment by Reginer** [comment]
I downloaded and maked AOSP，The classes-header.jar  was copied from its out folder.

**Comment by anggrayudi** [comment]
Ok, thanks @Reginer. I will test and merge it to master later.

**Comment by anggrayudi** [comment]
Pushed to the latest commit on master branch.
