### ISSUE TITLE
Android-30 missing apis from services.jar, framework-wifi.jar etc

### ISSUE THREAD

**Issue by map220v** [anggrayudi/android-hidden-api#82]
I Tried to use android.net.wifi.WifiSsid.createFromAsciiEncoded("") and com.android.server.SystemService but WifiSsid and SystemService classes is missing.

I found these classes in framework-wifi.jar and services.jar

Also it's seems that some of jar files from BOOTCLASSPATH doesn't exists in android-30.jar

**Comment by map220v** [comment]
Just made android.jar using android-30.jar from here as base
Added these libraries from bootclasspath:
android.net.ipsec.ike.jar
bouncycastle.jar
com.android.location.provider.jar
conscrypt.jar
ethernet-service.jar
ext.jar
services.jar
telephony-common.jar
framework-mediaprovider.jar
framework-permission.jar
framework-statsd.jar
framework-tethering.jar
framework-wifi.jar
ims-common.jar
okhttp.jar
service-permission.jar
updatable-media.jar
voip-common.jar

Jars i took from AOSP11 that i downloaded from google build server:
"https://ci.android.com/builds/branches/aosp-android11-gsi/grid?"

Modded android.jar:
"https://drive.google.com/file/d/1xHO36pEdL2QORER6OLm6eC_H4jhetntE/view?usp=sharing"

Not sure if it's fully works, but simple app compiles fine.

**Comment by anggrayudi** [comment]
Thanks, I've uploaded it.
