### ISSUE TITLE
For Android 12

### ISSUE THREAD

**Issue by AhmedX6** [anggrayudi/android-hidden-api#86]
Hello is it possible to have Android 12 hidden API jar file on drive ?

**Comment by CpuTurbo** [comment]
https://github.com/Reginer/aosp-android-jar

**Comment by Cristiandiazmolick** [comment]
I’m sorry but I never sent this nor any other email related to this matter

**Comment by CpuTurbo** [comment]
> @CpuTurbo as i could understand with the help of translator, there is a need now to make some additions instead of just replacing android.jar?

For you, just replace android.jar will work.

**Comment by AhmedX6** [comment]
Thanks a lot
