### ISSUE TITLE
Android API 31 - 32

### ISSUE THREAD

**Issue by abraaocaldas** [anggrayudi/android-hidden-api#88]
Hello, 

Any news on JAR for API 31 - 32? 

Thanks!

**Comment by DADi590** [comment]
In case anyone is really needing them, there's this repository from another Issue: https://github.com/Reginer/aosp-android-jar. Currently it has from 29 to 32. 30-32 seem to be working normally (didn't try 29, as that one I have from this repo).

**Comment by yq930825** [comment]
> In case anyone is really needing them, there's this repository from another Issue: https://github.com/Reginer/aosp-android-jar. Currently it has from 29 to 32, and all seem to be working normally.

33 and 34 has been added for now.
