### ISSUE TITLE
API 23 framework.jar - Finally (hopefully)

### ISSUE THREAD

**Issue by wasdennnoch** [anggrayudi/android-hidden-api#9]
Hi, I randomly looked at my /system/framework folder and guess what I found: A framework.jar! It even contains 2 dex files. I hope that you can do something with it :D

File: http://www.mediafire.com/download/lc34h900a13rb41/framework.jar

Device: SGS3 LTE with BlissPop ROM, Android 6.0.1, Bliss version v6.2

**Comment by anggrayudi** [comment]
Thanks @wasdennnoch. Also prepare yourself to the new limitation of this library. Android N with API level 24 will be released soon!

I also updated the sample app and library to use API 23.
